import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../components/layout.component'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
          <title>Case Worker</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
