import Head from 'next/head';
import type { AppProps } from 'next/app';
import { ThemeProvider } from "@mui/material/styles";
import { StyledEngineProvider } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";

import { createTheme } from '@mui/material/styles';
import { red } from '@mui/material/colors';

import '../styles/globals.css';
import AppLayout from '../components/layout.component';

// Create a theme instance.
const theme = createTheme({
  palette: {
    primary: {
      main: 'rgba(27, 24, 79, 1)',
    },
    secondary: {
      main: '#19857b',
    },
    error: {
      main: red.A400,
    },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
          <title>Case Worker</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
      </Head>
      <StyledEngineProvider>
        <ThemeProvider theme={theme}>
          {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
          <CssBaseline />
          <AppLayout Component={Component} pageProps={pageProps} />
        </ThemeProvider>
      </StyledEngineProvider>
    </>
  )
}
